<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StackDuel.Api\StackDuel.Api.csproj" />
    <ProjectReference Include="..\StackDuel.Application\StackDuel.Application.csproj" />
    <ProjectReference Include="..\StackDuel.Domain\StackDuel.Domain.csproj" />
    <ProjectReference Include="..\StackDuel.Infrastructure\StackDuel.Infrastructure.csproj" />
  </ItemGroup>

</Project>
