<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="User\Events\**" />
    <EmbeddedResource Remove="User\Events\**" />
    <None Remove="User\Events\**" />
  </ItemGroup>

</Project>
